# version: '2.17'

# services:
 
#  sample-react:
#    container_name: sample-react-dev
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/react-sample-app'
#      - '/react-sample-app/node_modules'
#    ports:
#      - 3001:3000
#    environment:
#      - CHOKIDAR_USEPOLLING=true