# build environment
FROM node:19.8.1-alpine3.17 as build
WORKDIR /react-sample-app
ENV PATH /react-sample-app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm run build

#production environment
FROM nginx:stable-alpine
COPY --from=build /sample-react-app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

